### ISSUE TITLE
Can this be modified to work with the hub?

### ISSUE THREAD

**Issue by evanrich** [bbostock/Switchbot_Py_Meter#1]
This is awesome, just picked up some of these meters, along with the hub.  Have not been able to find any documentation on the hub yet, wondering if we can pull via wifi to the hub, instead of BLE to the meters?  I've got 2 so far and would love to be able to graph the temps/humidity in grafana.  I've opened a ticket with Switchbot, but wondering if you have any knowledge yourself? 

Thanks!  Feel free to close since this isn't really an issue.

**Comment by bbostock** [comment]
It probably could be modified for the hub, but to he honest, that’s not part of my requirement for my home automation system. You can get further information in the hub from this link: https://github.com/OpenWonderLabs/python-host/wiki/Bot-BLE-open-API if you want to have a go yourself. 
Cheers, Bill
