### ISSUE TITLE
No module named bluepy

### ISSUE THREAD

**Issue by GreenBear33** [bbostock/Switchbot_Py_Meter#4]
Hi I am having trouble when I run the 

from bluepy import btle

I am getting the reply, No module name 'bluepy'.

Can you assist please?

**Comment by bbostock** [comment]
Hi,
Please refer to the information on the BluePy readme. 
https://github.com/IanHarvey/bluepy/blob/master/README.md
I suggest you double check the python 3 installation advice. 
Cheers
Bill

**Comment by GreenBear33** [comment]
Hi Bill, 

I checked for bluepy and i get the following:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: bluepy in /usr/local/lib/python3.7/dist-packages (1.3.0)

**Comment by GreenBear33** [comment]
I tried to run meters.py again and I get the following:

on_log: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k30) client_id=b''
[31mScanning for devices...[0mon_log: Received CONNACK (0, 0)

on_connect: MQTT connection returned result: Connection Accepted.
Traceback (most recent call last):
  File "/home/pi/switchbot/meters.py", line 157, in <module>
    main()
  File "/home/pi/switchbot/meters.py", line 154, in main
    devices = scanner.scan(30)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)
>>> on_log: Sending PINGREQ
on_log: Received PINGRESP
on_log: Sending PINGREQ
on_log: Received PINGRESP
on_log: Sending PINGREQ
on_log: Received PINGRESP
on_log: Sending PINGREQ
on_log: Received PINGRESP
on_log: Sending PINGREQ
on_log: Received PINGRESP
on_log: Sending PINGREQ
on_log: Received PINGRESP

**Comment by bbostock** [comment]
Hi, 
Are you using sudo to run the command? 
I get the same error if I don't use sudo.
Cheers
Bill
